### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by ferferga** [dmnsgn/media-codecs#3]
The current project doesn't work right with TypeScript, with a ts(7016) error when importing.
This makes me wonder is a migration to TS might be more desirable and is welcome in this project?

**Comment by dmnsgn** [comment]
Hi, for a package with a small and simple API surface like this one, I don't intend to migrate to TS as it would add complexity for little benefits.
But types are exported alongside the package, auto generated from JSDoc. In my test (new ts project, importing the usage from README and compiling), I don't have any issue seeing the types in VSCode, do you have any more details on that TS issue?

**Comment by ferferga** [comment]
Can you share with me the repo of that barebones project so I can try to reproduce it on top of it?

**Comment by dmnsgn** [comment]
Here you go [test-media-codecs.zip](https://github.com/dmnsgn/media-codecs/files/15462054/test-media-codecs.zip)
Running `tsc` (Version 5.4.5) and I don't see any errors.
If you can share your tsconfig.json, tsc version and maybe a reduced test case, that could help. And also the full error.

I have a hunch that since typescript 4.7, [things have changed on how TS is resolving types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing), and I might need to change my exports field in package.json for it to work?

**Comment by dmnsgn** [comment]
The above ts(7016) error should be fixed and you can import types at the root: `import type { AVCCodecOptions } from "media-codecs";`

**Comment by ferferga** [comment]
@dmnsgn Apologize for no replying in a long time. I didn't forget about this, but I got it sidetracked due to exams.

Will check your fix when time permits and report back, no matter if for good or bad. If I recall correctly, I think I also have some improvement ideas for HEVC, so you might see a PR from me as well :P.

Thank you very much for your fix!
